src/clj_http/lite/util.clj

Hi
And thanks for a fine project!
When using clj-http-lite with GraalVM 19.3, I'm getting a strange stacktrace exception:
```
JVM Exception: #error {
:cause java.net.URLEncoder
:via
[{:type java.lang.ClassNotFoundException
:message java.net.URLEncoder
:at [com.oracle.svm.core.hub.ClassForNameSupport forName ClassForNameSupport.java 60]}]
:trace
[[com.oracle.svm.core.hub.ClassForNameSupport forName ClassForNameSupport.java 60]
[java.lang.Class forName DynamicHub.java 1197]
[clojure.lang.RT classForName RT.java 2204]
[clojure.lang.RT classForName RT.java 2213]
[clj_http.lite.util$url_encode invokeStatic util.clj 28]
[clj_http.lite.client$generate_query_string$fn__1889 invoke client.clj 150]
...
```
Adding these type hints solves this problem.
Would that be OK to include in the project? …

Add type hints for GraalVM

---

CHANGELOG.md
src/clj_http/lite/client.clj
src/clj_http/lite/links.clj
test/clj_http/test/links_test.clj

In https://github.com/whitepages/github-changelog/pull/72 we ran into a problem where [clj-http](https://github.com/dakrone/clj-http) is too heavy for our usecase but `clj-http-lite` doesn't support the parsing of link headers.
It appears to me that the original clj-http-lite project had been forked from clj-http before link parsing support was added to the latter.
It appears fairly light so I took the courage to suggest porting it to this project. Please let me know your thoughts wrt this.

Add parsing of link headers

---

Readme.md

The link to Clojars was pointing to `clj-http-lite/clj-http-lite` on Maven. Updated it to `org.martinklepsch/clj-http-lite` 🙂

Update link to Clojars

---

project.clj
src/clj_http/lite/client.clj
src/clj_http/lite/core.clj
src/clj_http/lite/links.clj
src/clj_http/lite/util.clj

[#8] fix reflection warning

---

.circleci/config.yml
.travis.yml
Readme.md
project.clj
src/clj_http/lite/client.clj
src/clj_http/lite/core.clj
test-resources/logback.xml
test/clj_http/test/client.clj
test/clj_http/test/core.clj
test/clj_http/test/links_test.clj
test/setup.clj

Various things I did in preparation for https://github.com/martinklepsch/clj-http-lite/issues/10. I tried to keep every commit semantic and reviewable on its own. They go as follows:
* Remove unused `ring/ring-devel`
* Mark :test dependencies as such
* This tends to be cleaner - it's the "deps.edn" way, which we can follow even when using Lein :)
* `:test-selectors`: default to running all tests
* This is safer, especially for the CI integration.
* Setup logging
* This silences Jetty logging, which can be otherwise noisy, especially when using the `:port 0` option.
* Satisfy clj-kondo and Eastwood
* Use randomized ports in tests
* This yields an overall cleaner pattern, avoiding a defonce, possible interference with other processes, etc.
* Remove some commented-out tests
* Persistent …

Cleanup project

---

.github/workflows/ci.yml

Add Windows to test matrix for jvm and bb tests
No longer failing fast on first matrix job failure
Bump GitHub actions
Employ deps cache
Switch to temurin for Java vendor
Report which tools versions were installed
Download deps prior to running main clj jvm action
Closes #21

ci: add windows to matrix, freshen config

---

CHANGELOG.md
src/clj_http/lite/client.clj
test/clj_http/test/client.clj
test/clj_http/test/core.clj

Was previously always encoding to system default character encoding,
which is UTF-8 unless on Windows then it is windows-1252.
Now:
- encoding body to requested body encoding
- and defaulting to UTF-8 if no body encoding is requested
Also:
- Added extended characters to http bodies in tests to exercise
body encoding/decoding
- Verified :auto body decoding with an extra test
Note that :auto body decoding might not be entirely correct.
It will only look at content-type charset if content-type starts with
"text/". Diagnosing/fixing this is out of scope for this PR.
Fixes #18

Body encoding now applied and always defaults to UTF-8

---

deps.edn
test/clj_http/test/client_test.clj
test/clj_http/test/cookies_test.clj
test/clj_http/test/core_test.clj

It is what most folks and tools expect these days.
Closes #35

tests: rename test namespaces to end in -test

---

doc/cljdoc.edn
src/clj_http/lite/client.clj
src/clj_http/lite/core.clj
src/clj_http/lite/links.clj
src/clj_http/lite/util.clj

This exercise helped me to understand the API more deeply, hopefully it
will help our users too.
The biggest challenge was documenting `clj-http.lite.client/request`.
Its previous docstring was way too vague for me to understand, as a
user, what is available.
Also challenging is the lack of definition of the supported API.
I'm guessing our documented API is currently including lots of
unnecessary internals.
I reviewed all existing docstrings and updated where I thought I could
be clearer and/or more consistent. I added no new docstrings.
Also: added cljdoc.edn to explicitly list our docs.
Closes #36

docs: review and update docstrings

---

CHANGELOG.md
README.md
src/clj_http/lite/client.clj
test/clj_http/test/client_test.clj

Brought over flattening code from clj-http but not the options to
enable/disable flattening.
For us, for now, it is always enabled.
See updates to README for examples.
Closes #43

Flatten nested query and form parameter maps

---

CHANGELOG.md
bb/clj_http/lite/client_test.clj
src/clj_http/lite/core.clj
test/clj_http/test/core_test.clj

Was formerly also being applied to all subsequent requests.
This change does break insecure? for current babashka (v0.9.161) which
does not currently allow setHostnameVerifier and setSSLSocketFactory to be called
on a HttpsURLConnection.
Closes #45

Apply :insecure? ssl opt only to current request

---

test/clj_http/test/core_test.clj

And now correctly using `:server-port` instead of `:port`.
Closes #52

tests: server-name no longer includes port

---

README.md

Be more vague and point to Graal docs.
A "known issue" implies a bug, rename to "tip".

docs: rework graal vm native image tip [skip ci]

---

test/clj_http/lite/client_test.clj
test/clj_http/lite/integration_test.clj

All integration share same test fixture setup, so it makes sense to have
them together.
No need for ^integration metadata on tests any more, they are grouped by
namespace now.

test refactor: group all integration tests

---

.gitignore
README.md

Resolves #51
Signed-off-by: Anders Eknert <anders@eknert.com>

Add example of mocking using with-redefs

---

README.adoc
bb/tasks.clj
doc/01-user-guide.adoc
doc/02-developer-guide.adoc
doc/03-maintainer-guide.adoc
doc/cljdoc.edn

Also add:
- Credit for contributors (just text for now)
- Interesting alternatives to clj-http-lite
- Info on supported and dev environments
- Dev contributing guidance

docs: split out README to guides [skip ci]

---

test/clj_http/lite/integration_test.clj

Babashka v0.9.162 now includes formerly missing exceptions

tests: revert change for missing bb exceptions

---

doc/01-user-guide.adoc

Add org.babashka/http-client
State min jdk version for other alternatives.
Add note on babashka.curl.

docs: update interesting alternatives

---

.clj-kondo/http-kit/http-kit/config.edn
.clj-kondo/http-kit/http-kit/httpkit/with_channel.clj
.github/workflows/publish.yml
.github/workflows/shared-setup/action.yml
.github/workflows/tests.yml
bb.edn
deps.edn
doc/01-user-guide.adoc
script/test_jvm.clj
test/clj_http/lite/test_util/http_server.clj

Of note:
- turfed: bb no longer needs https://github.com/babashka/tools.namespace to run tests
- bumping ring-jetty-adapter required small test code change
- now also testing against clojure 1.12
- now also testing against jdk 21

maint: bump deps (ci and test only)

---

.clj-kondo/taoensso/encore/config.edn
.clj-kondo/taoensso/encore/taoensso/encore.clj
bb.edn
deps.edn

Bump test and build deps (including latest clojure 11 and 12-alpha).
Added an `outdated` task to add some antq configuration to document/express that we don't want to move to any deps that are not jdk8 compatible.
Checked in some 3rd party lib lint config clj-kondo found.

test & dev & ci: bump deps, add outdated task

---

bb.edn
deps.edn
script/publish.clj

Of note:
- clojure 1.12 beta2!
- bb `pubcheck` task can now run checks on unpushed branch

test & ci: bump deps, tweak pubcheck

---

bb.edn
deps.edn
script/lint.clj

Of note:
- clojure 1.12.0! woot!
- new version of clj-kondo - we can now build cache and copy configs in one step

test & ci: bump deps
